replicaCount:
  backend: 2
  frontend: 2

image:
  backend:
    repository: kubeops-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: kubeops-frontend
    tag: latest
    pullPolicy: IfNotPresent

service:
  backend:
    type: ClusterIP
    port: 8080
  frontend:
    type: LoadBalancer
    port: 80

resources:
  backend:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  frontend:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

mode: release
